spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-3.cloud-iam.com/auth/realms/me-fit-keycloak
          jwk-set-uri: https://lemur-3.cloud-iam.com/auth/realms/me-fit-keycloak/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never #correct way for deploy
      platform: postgres   # Added configuration
react:
  address: https://me-fit-frontend.vercel.app/
logging:
  level:
    org.hibernate.stat: debug
